### ISSUE TITLE
500 Internal Server error

### ISSUE THREAD

**Issue by uzi0espil** [vidartf/jupyterlab_discovery#8] opened 2018-07-20 14:26 UTC
Hi, I am a big fan.

I have stumbled into 500 internal server error after installing jupyter-discovery

here is the log:

```
Uncaught exception GET /discovery/api/extensions?1532096467757 (192.168.2.165)
    HTTPServerRequest(protocol='http', host='192.168.2.151:8888', method='GET', uri='/discovery/api/extensions?1532096467757', version='HTTP/1.1', remote_ip='192.168.2.165')
    Traceback (most recent call last):
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_discovery/handlers.py", line 276, in get
        extensions = yield self.manager.list_extensions()
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_discovery/handlers.py", line 101, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_discovery/handlers.py", line 166, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/ioloop.py", line 759, in _run_callback
        ret = callback()
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/ioloop.py", line 780, in _discard_future_result
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_discovery/handlers.py", line 198, in _load_outdated
        tuple(info['extensions'].keys())
      File "/home/compredict/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_discovery/handlers.py", line 214, in _latest_compatible_package_versions
        metadata = _fetch_package_metadata(handler.registry, name, self.log)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab/commands.py", line 1588, in _fetch_package_metadata
        return json.load(response)
      File "/usr/lib/python3.5/json/__init__.py", line 268, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
        s.__class__.__name__))
    TypeError: the JSON object must be str, not 'bytes'
```
What do you think went wrong?

**Comment by vidartf** [comment] 2018-07-24 10:56
Seems like a missed decode step before sending the HTTP response to the json library. I'll have a look at it next week, as I might have fixed this somewhere else.

**Comment by uzi0espil** [comment] 2018-08-01 10:02
Any luck with it?

**Comment by vidartf** [comment] 2018-08-01 10:56
This is an error with the code in Jupyterlab. I'll submit a fix for that to jupyterlab. I think maybe the error was triggered by problems with NPM search last week.

FYI, jupyterlab discovery has been integrated into the newest version of jupyterlab, but is behind a setting (it will need to be enabled manually). As such, you might have more luck with that.

As the problem is upstream, I'm closing this issue. Feel free to comment if there are anything else to consider!

**Closed as completed by vidartf** 2018-08-01 10:56 UTC

**Comment by vidartf** [comment] 2018-08-01 11:00
Actually, the issue has been fixed in the latest release of jupyterlab, so there's nothing to upstream.
